### ISSUE TITLE
Feature request: Enable progress status

### ISSUE THREAD

**Issue by vdun** [lorenzog/dns-parallel-prober#9]
- Progress bar, percentage, request 30/1000, ...
- Write directly to the out file and not by finishing the enum
so one can stop and then resume for example.

**Comment by lorenzog** [comment]
Hi,
That sounds sensible. Care to submit a pull request?

**Comment by lorenzog** [comment]
Hi @vdun 

Sorry it took me a while but I've finally got to your request. I've added a progress bar in the last commit. If you get the chance, please give it a go and let me know how it looks.

**Comment by lorenzog** [comment]
Hi @vdun -- the latest update will write to file as hosts are discovered in realtime so there's no need for it to finish.
